// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSOgZ6sei5AlBJxZ17G1vk5T2SvOqAL1k',
    appId: '1:867740997922:web:939707727a3b1542236d7b',
    messagingSenderId: '867740997922',
    projectId: 'studymaterialchatboat',
    authDomain: 'studymaterialchatboat.firebaseapp.com',
    storageBucket: 'studymaterialchatboat.appspot.com',
    measurementId: 'G-RDN59NCK1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3MfNpN0_UPBtK-ZmDtWYOqxn0Mhz6bBI',
    appId: '1:867740997922:android:67dab1ed4057a0f5236d7b',
    messagingSenderId: '867740997922',
    projectId: 'studymaterialchatboat',
    storageBucket: 'studymaterialchatboat.appspot.com',
  );
}
